config/routes.rb
Rails.application.routes.draw do
  # Sign in / Sign up
  resources :users, only: [:new, :create]
  resource :session, controller: 'session', only: [:new, :create, :destroy]
  
  # Resources
  resource :current_user, controller: 'current_user', only: [:edit, :update]
  resources :sites, only: [:index, :new, :create, :edit, :update, :destroy]
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Check if a domain has been registered to our application (endpoint required by the CaddyServer)
  get "check_domain" => 'check_domain#show'

  # Root of the main domain -> sign up page
  get '/' => 'users#new', constraints: { host: Rails.application.config.x.main_host }

  # Sitemap of the demo app
  get '/sitemap.xml', to: 'sitemap#index', constraints: { host: Rails.application.config.x.main_host }

  # [Maglev] For more information, go to https://doc.maglev.dev
  # [Maglev] Editor UI + preview endpoint
  mount Maglev::Pro::Engine => '/maglev', as: :maglev

  # [Maglev] Sitemap.xml (depends on the host of the request)
  get '/sitemap.xml', to: 'maglev/sitemap#index', constraints: Maglev::PreviewConstraint.new(preview_host: true)

  # [Maglev] catch all the routes (depends on the host of the request)
  get '(*path)', to: 'maglev/page_preview#index', defaults: { path: 'index' }, constraints: Maglev::PreviewConstraint.new
end

app/views/shared/_demo_banner.html.erb
<div class="flex items-center justify-center gap-x-6 bg-gray-900 px-6 py-2.5 sm:px-3.5">
  <p class="text-sm leading-6 text-white">    
    <strong class="font-semibold">This is a demo platform powered by <%= link_to 'Maglev', 'https://www.maglev.dev', class: 'underline', target: '_blank' %>, our site builder in Rails</strong>
    <svg viewBox="0 0 2 2" class="mx-2 inline h-0.5 w-0.5 fill-current" aria-hidden="true"><circle cx="1" cy="1" r="1" /></svg>
    <a href="https://github.com/maglevhq/site-builder-demo" target="_blank">
      Check out the source code <i class="ri-github-fill"></i> &nbsp;<span aria-hidden="true">&rarr;</span>
    </a>
  </p>
</div>

app/views/shared/_menu.html.erb
<div class="sm:-my-px sm:ml-12 sm:flex sm:space-x-8">
  <%= link_to 'Sites', sites_path, class: main_menu_item_css(:sites) %>
</div>

app/views/shared/_profile_dropdown.html.erb
<%= render_ncuikit :menu_dropdown, orientation: 'right', content_class: 'w-48', arrow: true do |c| %>
  <% c.with_label do %>
    <%= render_ncuikit :avatar, url: current_user.avatar, full_name: nil, size: 'sm' %>
  <% end %>

  <% c.with_menu_header do %>
    <p class="text-sm">Signed in as</p>
    <p class="truncate text-sm font-medium text-gray-900">
      <%= current_user.email %>
    </p>
  <% end %>

  <% c.menu_item do %>
    <%= link_to 'Edit profile', edit_current_user_path, class: c.menu_item_css %>
  <% end %>

  <% c.menu_separator %>

  <% c.menu_item do %>
    <%= button_to 'Sign out', session_path, method: :delete, class: c.menu_item_css %>
  <% end %>
<% end %>

app/views/shared/_toast.html.erb
<% flash.each do |type, msg| %>
  <%= render_ncuikit :toast, type: type == 'notice' ? 'success' : type, title: msg %>
<% end %>