config/routes.rb
Rails.application.routes.draw do
  # Sign in / Sign up
  resources :users, only: [:new, :create]
  resource :session, controller: 'session', only: [:new, :create, :destroy]
  
  # Resources
  resource :current_user, controller: 'current_user', only: [:edit, :update]
  resources :sites, only: [:index, :new, :create, :edit, :update, :destroy]
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Check if a domain has been registered to our application (endpoint required by the CaddyServer)
  get "check_domain" => 'check_domain#show'

  # Root of the main domain -> sign up page
  get '/' => 'users#new', constraints: { host: Rails.application.config.x.main_host }

  # Sitemap of the demo app
  get '/sitemap.xml', to: 'sitemap#index', constraints: { host: Rails.application.config.x.main_host }

  # [Maglev] For more information, go to https://doc.maglev.dev
  # [Maglev] Editor UI + preview endpoint
  mount Maglev::Pro::Engine => '/maglev', as: :maglev

  # [Maglev] Sitemap.xml (depends on the host of the request)
  get '/sitemap.xml', to: 'maglev/sitemap#index', constraints: Maglev::PreviewConstraint.new(preview_host: true)

  # [Maglev] catch all the routes (depends on the host of the request)
  get '(*path)', to: 'maglev/page_preview#index', defaults: { path: 'index' }, constraints: Maglev::PreviewConstraint.new
end

app/controllers/current_user_controller.rb
class CurrentUserController < ApplicationController
  before_action :verify_user_authorization
  before_action :set_user, only: %i[edit update]

  # GET /current_user/edit
  def edit
  end

  # PATCH/PUT /current_user or /current_user.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to sites_path, notice: "Your profile was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!
    session[:user_id] = nil

    respond_to do |format|
      format.html { redirect_to new_session_path, notice: "Your account was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(current_user.id)
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:avatar, :email, :password, :password_confirmation)
    end
end

app/views/current_user/edit.html.erb
<%= render_ncuikit :page_layout, title: 'Editing your account' do |page| %>

  <%= form_with(model: @user, url: current_user_path) do |form| %>
    <div class="grid grid-cols-1 gap-x-6 gap-y-6 sm:grid-cols-6">
      <div class="sm:col-span-3">
        <%= render_ncuikit_form :avatar_field, form: form, attribute: :avatar %>
      </div>
      <div class="sm:col-start-1 sm:col-span-3">
        <%= render_ncuikit_form :email_field, form: form, attribute: :email %>
      </div>

      <div class="sm:col-start-1 sm:col-span-3">
        <%= render_ncuikit_form :password_field, form: form, attribute: :password %>
      </div>

      <div class="sm:col-span-3">
        <%= render_ncuikit_form :password_field, form: form, attribute: :password_confirmation %>
      </div>
    </div>

    <div class="mt-12 text-right border-t border-gray-900/10 pt-6">
      <%= render_ncuikit_button :primary_submit, label: 'Update', size: 'lg' %>
    </div>
  <% end %>
<% end %>